### ISSUE TITLE
https://icon.wuruihong.com 好像挂了

### ISSUE THREAD

**Issue by Hext123** [zhanghuanchong/icon-workshop#10]
https://icon.wuruihong.com 好像没法正常使用了

另外我想自己搭一个也没搭起来, 😂,非专业PHP, 只知道搭常规的PHP项目

**Comment by zhanghuanchong** [comment]
抱歉，网站服务已恢复。系统默认使用 ImageMagick 处理图像，所以需要安装其命令行工具，以及 PHP 的 Imagick 扩展。参考：
* https://www.imagemagick.org/script/index.php
* http://php.net/manual/zh/book.imagick.php
