### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by visionxk** [zhanghuanchong/icon-workshop#13]
请问这是开源的并可使用的吗？

**Comment by zhanghuanchong** [comment]
是的。

**Comment by visionxk** [comment]
您能帮忙配置一下吗，我这边将通过电子邮箱联系您？

**Comment by visionxk** [comment]
我这边进入服务器界面的public/index.php界面显示错误为：

Warning: require(/www/wwwroot/Icon/public/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/Icon/public/index.php on line 24

Fatal error: require(): Failed opening required '/www/wwwroot/Icon/public/../vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/Icon/public/index.php on line 24
