### ISSUE TITLE
这个关不掉呀

### ISSUE THREAD

**Issue by lifetin** [zhanghuanchong/icon-workshop#17]
![44](https://user-images.githubusercontent.com/10474968/56177881-d0d8a100-6032-11e9-82c4-bda9494f020c.png)
这个关不掉呀.鼠标移上是禁止状态.

**Comment by zhanghuanchong** [comment]
@lifetin 现在好了吗？我这里无法复现。

**Comment by lifetin** [comment]
之前出现了. 现在没出现了. 不知道什么原因. 
再遇到我写下操作流程

**Comment by zhanghuanchong** [comment]
@lifetin 好的，谢谢。
