### ISSUE TITLE
打开你这个网站电脑内存飙升

### ISSUE THREAD

**Issue by lixuedong1024** [zhanghuanchong/icon-workshop#19]
ubuntu1804  8G内存  卡关机了 win10 顿时chrome 占两G

**Comment by OrangePiPiPiPi** [comment]
+1,打开网站浏览器卡死，电脑呼呼响，我电脑Mac Pro

**Comment by zhanghuanchong** [comment]
@lixuedong1024 @OrangePiPiPiPi 是打开哪个页面卡？做了什么操作之后卡？

**Comment by OrangePiPiPiPi** [comment]
进入制作启动图那个页面（https://icon.wuruihong.com/splash），什么也不操作，进去两三秒后浏览器就卡死了

**Comment by lixuedong1024** [comment]
我也是 打开制作启动图的页面
打开网页瞬间流畅
上传图片之后就卡了
操作就开始无响应了
慢慢会把内存占满

**Comment by zhanghuanchong** [comment]
多谢反馈，我看一下。

**Comment by zhanghuanchong** [comment]
@lixuedong1024 @OrangePiPiPiPi 已修复，是留言插件畅言造成的。我们抽空会将其替换成自己的。
