### ISSUE TITLE
 Ios生成的图标：PNG透明背景原图片，生成后变成了白色背景效果图标了

### ISSUE THREAD

**Issue by XiaBaKe** [zhanghuanchong/icon-workshop#2]
设置透明色还是一样,而且会一直卡在生成图标界面

**Comment by rtsbtx** [comment]
> iOS系统的图标本身就不支持透明色，默认的透明色会被白色填充，你也可以打开“可选参数”来设置背景色：
> 
> ![image](https://user-images.githubusercontent.com/3062319/41610709-7d40daca-7420-11e8-8ce4-5cc02f043e3a.png)
> 
> > 而且会一直卡在生成图标界面
> 
> 请重试。如果还不行，请将你上传的图片发给我看看

iOS是支持透明背景的png的
