### ISSUE TITLE
开源了一下，支持直接拖动图片

### ISSUE THREAD

**Issue by kuaifan** [zhanghuanchong/icon-workshop#22]
开源了一下，支持直接拖动图片，欢迎讨论 https://console.weiui.app/#/tools/launchimage

**Comment by zhanghuanchong** [comment]
整的不赖，源码地址在哪里？没有fork? 可否提交 pr?

**Comment by kuaifan** [comment]
可以，抽个空pr下

**Comment by zhanghuanchong** [comment]
@kuaifan 
我看到 https://eeui.app/guide/launch.html 里链接到了你的更新页面，并未标注使用了本站的开源代码，也未链接到我的站点。

请注意本软件的开源协议是 **AGPL**: https://github.com/zhanghuanchong/icon-workshop/blob/master/LICENSE
中文介绍参考：http://ewen0930.github.io/2016/11/open-source-licenses/

希望你能遵守开源社区规则，感谢你的配合。

**Comment by kuaifan** [comment]
一直忙，已经提交pr，欢迎交流https://github.com/zhanghuanchong/icon-workshop/pull/23

**Comment by zhanghuanchong** [comment]
谢谢，我看一下。
