### ISSUE TITLE
添加一个 Mac 图标的生成呗

### ISSUE THREAD

**Issue by SSBun** [zhanghuanchong/icon-workshop#26]
Mac 开发也有啊

**Comment by zhanghuanchong** [comment]
@SSBun 感谢建议，我抽空加一下。

**Comment by zhanghuanchong** [comment]
@SSBun 已添加 mac app 图标支持：
![image](https://user-images.githubusercontent.com/3062319/63914814-d923fc80-ca66-11e9-8caa-80ffdfb690fb.png)
![image](https://user-images.githubusercontent.com/3062319/63914779-c3163c00-ca66-11e9-866e-125a2b43d033.png)
