### ISSUE TITLE
上传图片 提示文件无效

### ISSUE THREAD

**Issue by tomUp** [zhanghuanchong/icon-workshop#27]
![1024x1024](https://user-images.githubusercontent.com/21700133/61428257-ec19bc00-a953-11e9-825b-e915de0db9a5.png)

**Comment by tomUp** [comment]
@zhanghuanchong

**Comment by zhanghuanchong** [comment]
@tomUp 已恢复服务。抽空优化一下。

**Comment by tomUp** [comment]
> @tomUp 已恢复服务。抽空优化一下。

感谢~
