### ISSUE TITLE
希望可以选择下载尺寸

### ISSUE THREAD

**Issue by rakuyoMo** [zhanghuanchong/icon-workshop#28]
对于 iOS 图标而言，不同的 iOS 版本需要不同尺寸的App 图标。

就我们的项目而言，50、57、72 尺寸的 图片是不需要的，每次我都需要手动从 Contents.json 中删除它们，再删除图片，非常麻烦。

而且我们还采用了组件化开发，每个组件都想添加一个 App 图标，这样就会有好几套 App 图标，删除的工作量非常繁琐

**Comment by zhanghuanchong** [comment]
感谢反馈，我们会抽空改进一下。

**Comment by rakuyoMo** [comment]
> 感谢反馈，我们会抽空改进一下。

希望可以尽快实现，期待！

**Comment by zhanghuanchong** [comment]
@rakuyoMo 
已默认剔除 iOS 5,6 的图标，并添加选项可以手动开启：

![image](https://user-images.githubusercontent.com/3062319/63906401-4a08eb80-ca4a-11e9-83a4-a60264ab20e7.png)
