### ISSUE TITLE
启动图怎么生成gif

### ISSUE THREAD

**Issue by Coder108** [zhanghuanchong/icon-workshop#29]

**Comment by zhanghuanchong** [comment]
@Coder108 启动图是 iOS 和 Android 的应用启动时的等待图，不支持 gif。你的应用场景是什么？

**Comment by Coder108** [comment]
我是想启动图有个loading动画

**Comment by Coder108** [comment]
> @Coder108 启动图是 iOS 和 Android 的应用启动时的等待图，不支持 gif。你的应用场景是什么？

我是想启动图有个loading动画

**Comment by zhanghuanchong** [comment]
@Coder108 抱歉，暂时不支持，目前也没有计划。
