### ISSUE TITLE
不支持的文件格式 PSD

### ISSUE THREAD

**Issue by Co2333** [zhanghuanchong/icon-workshop#5]
![image](https://user-images.githubusercontent.com/25259084/47917381-4cf78600-dee4-11e8-9a3e-3231a8ce6404.png)
[icon.psd.zip](https://github.com/zhanghuanchong/icon-workshop/files/2542540/icon.psd.zip)

**Comment by zhanghuanchong** [comment]
@Co2333 
抱歉，使用你的附件无法复现。可以上传并生成成功：https://icon.wuruihong.com/icon?utm_source=ZsV8kqNO#/ios

![image](https://user-images.githubusercontent.com/3062319/47959386-a1eae780-e01d-11e8-9209-dab1a8c67174.png)


请提供更多信息。
