### ISSUE TITLE
图标变形问题看不到吗

### ISSUE THREAD

**Issue by qssq** [zhanghuanchong/icon-workshop#53]
我的长图标变形了。变成匾的了

**Comment by zhanghuanchong** [comment]
@qssq  目前只支持正方形的图标。请问你的长方形图标的应用场景是什么？我们会考虑加上支持。谢谢。

**Comment by zhanghuanchong** [comment]
@qssq 当添加的图片是长方形时，现在支持设置显示的位置和缩放规则：

![image](https://user-images.githubusercontent.com/3062319/147714443-b5f83391-5cd8-492b-b9cd-81982f358c93.png)

**Comment by lozn00** [comment]
thank,

**Comment by lozn00** [comment]
其实我上传的是透明图片，应该自动识别为最大长度滴
