### ISSUE TITLE
Mac OS生成的图标不能背景透明

### ISSUE THREAD

**Issue by sunjianan9900** [zhanghuanchong/icon-workshop#56]
不支持自动圆角，提交带圆角的PNG无法生成透明的，背景颜色变成白色了
选择背景色为透明，也不行

**Comment by Hext123** [comment]
+1  iOS图标也不能透明, 设置透明无效   (虽然AppStore不允许透明, 但是我不上AppStore)

**Comment by zhanghuanchong** [comment]
macOS 图标已支持圆角，感谢反馈
