### ISSUE TITLE
图标工厂图标生成后无法下载

### ISSUE THREAD

**Issue by xiaoYI999** [zhanghuanchong/icon-workshop#59]
![image](https://user-images.githubusercontent.com/52921324/193013373-7d83bc2d-1288-46e9-a58f-dc4698c3ffa8.png)
考虑资源是否丢失

**Comment by Richard-Choooou** [comment]
用postman下载

**Comment by zhanghuanchong** [comment]
历史问题，已增加服务器网络带宽
