### ISSUE TITLE
出现itms-90022错误

### ISSUE THREAD

**Issue by smallevil** [zhanghuanchong/icon-workshop#9]
Contents.json产生后,新的xcode上传,会报错说缺少120x120和57x57两张图

**Comment by zhanghuanchong** [comment]
![image](https://user-images.githubusercontent.com/3062319/49812895-5d333880-fda1-11e8-91e6-1bb5a69ba618.png)
抱歉无法复现，生成的有这两张图。请检查是否导入到 Xcode 后又进行了其他操作。请尝试重新生成。

**Comment by smallevil** [comment]
是挺奇怪的.
因为我也看这个json了,确实是有的.
但是在xcode 10.1,上传app store时,又确实有提示少120x120和57x57
